#!/bin/bash

# NOTE: This is a SERVER script!

echo
cd
  echo a$PATH
  echo b$NVM_DIR
  source $NVM_DIR/nvm.sh

appname=mish
#imdbhome=/home/minneadmin # default
imdbhome=/media/raid0 # server datastore
imdbroot=MISH # preselected
#imdbroot="''" # user selects
port=3000

# Add root link (rln)
ln -sTf / rln

# Add link to the text (document) directory (if present in imdbroot)
textdir=$imdbhome/$imdbroot/text
if [ -d $textdir ]; then ln -sTf $textdir public/text; fi

#ln -sTf $imdbhome/$imdbroot/text public/text
#rm -rf public/awstats public/awstats-icon public/cgi-bin

# Add links and a working directory for Awstats
#ln -sTf /usr/share/awstats/icon public/awstats-icon
#ln -sTf /usr/lib/cgi-bin public/cgi-bin
#mkdir public/awstats

# Add link for the old phpmyadmin
#rm -rf public/phpmyadmin
#ln -sT /usr/share/phpmyadmin public/phpmyadmin

#echo "Yarn replaces 'npm install'"
#echo -n "  Run yarn? (y/N): "

# echo -n "  Run npm install? (y/N): "
# read yN
# echo
# if [[ $yN == "y" || $yN == "yes" ]]; then
#   nvm ls
#   nvm use v14.17 # important to use right node version
#   npm install # Update node_modules using package.json
# #  npm install --verbose # Use --verbose to investigate hangings etc.
#   # ... changed dec.2018 to yarn, reverted july 2019
#   #sudo yarn  # Update node_modules using package.json
#   echo "##### Deployment is complete if no errors or severe complains appeared"
# fi


echo "##### Delete the $appname service"
pm2 delete $appname
echo "##### Start the $appname service"
pm2 -l /tmp/nodelog  start server.js -i 0 --name $appname -- $imdbhome $imdbroot $port
# Use one instance non-cluster mode (remove '-i 0'):
#pm2 -l /tmp/nodelog  start server.js --name $appname -- $imdbhome $imdbroot $port

cd ~
pm2 logs --lines 12 $appname
