#!/bin/bash

#" Remember to set the project durectory: "
#project=/home/tore/Arbeten/mish
project=/home/tore/Arbeten/mish-dev
echo $project

port=3000
# Kill the process (if any) already listening to this port
prid=`lsof -t -i:$port`
if [ $prid ]; then
  echo "Port $port is occupied by a process with pid=$prid;"
  echo -n "Kill the process and continue? (y/N): "
  read yN
  if [[ $yN != 'y' && $yN != 'yes' ]]; then
    echo "Cancelled"
    exit
  fi
  sudo kill $prid
fi

# Make the script usable from any directory
cd $project

#IMDB_HOME=/mnt/sda2
#IMDB_HOME=/mnt/koofrwebdav
IMDB_HOME=/home/tore
#IMDB_ROOT=MISH
#IMDB_ROOT=Framkallning_2019
IMDB_ROOT=Album-1
IMDB_ROOT='""' # NOTE: An 'empty' argument must be `'""'` in order to be
################   passed correctly positioned into `node server.js ...`
if [[ $1 ]]; then
  IMDB_HOME=$1
  if [[ $2 ]]; then
    IMDB_ROOT=$2
  fi
fi
echo IMDB_HOME = $IMDB_HOME
echo IMDB_ROOT = $IMDB_ROOT
echo -n "##### Starting the Node server "`date`

# Note that Node JS may be installed as either 'node', 'nodejs', or both
# Start the Express server. NOTE: server.js contains `... require ('express')`
node server.js $IMDB_HOME $IMDB_ROOT $port
