#!/bin/bash

scriptname=`basename $0`

if [[ $# != 1 && $# != 2 ]];	then
  echo "MISH UTILITY SCRIPT"
  echo "     Use: $scriptname <image file (TIFF, JPEG, ...)> [<tmpdir/>]"
	echo "   Makes: a temporary png file in directory \$PWD or <tmpdir/>"
	echo "          from the image file, renamed 012345<6 hex numbers>.png"
#	echo "          from the image file, renamed 012345<6 hex numbers>"
  echo "          (any 012345* file in the directory is first removed)"
	echo "  Output: the temporary <file name>"
	echo "Requires: convert of Imagemagick and openssl"
	exit 0
fi

dir=$PWD/
if [[ $# == 2 ]]; then
	dir=$2
fi

# remove old files
rm -f ${dir}012345*

# temporary file name with 6-digit hexadecimal random number
tmp=012345`openssl rand -hex 6`
#touch ${dir}$tmp.err

convert -strip -interlace PNG $1 -depth 8 ${dir}${tmp}.png
echo -n $tmp.png
#convert -strip -interlace PNG $1 -depth 8 ${dir}${tmp}
#echo -n $tmp
exit 0
