#! /bin/bash

XMP1='Xmp.dc.description'
XMP2='Xmp.dc.creator'

if [[ $# = 2 ]]; then
  text=$2
  files=$1
  for file in $files; do
    exiv2 -M"del $XMP2" "$file" 
    exiv2 -M"set $XMP2 $text" "$file"
  done
else
  echo " MISH UTILITY SCRIPT"
	echo " Usage: "`basename $0`" <string with image file name(s)> <text string>"
	echo "  Sets $XMP2 as the utf-8 text string"
	echo " Needs: exiv2"
fi
