#!/bin/bash
#
# Xmp.dc.<key> in
# image metadata   GUI name
# ---------------  --------------------------------------------
# description      Description (where-what-who?)
# creator          Origin/copyright etc.
# subject          Additional keywords (separated by semicolons)
# title            Image identity/archive number
# rights           Copyright
# source           Preliminary/supplementary/uncertain...
key=''
keys='description creator subject title rights source'
keyname=''
fil=''
txt='<text string>'
if [ $1 ]; then key=$1; fi
if [ $2 ]; then fil=$2; fi
for name in $keys; do
  if [[ $key == $name ]]; then
    keyname=$name
  fi
done
if [[ $keyname != '' && $# == 2 ]]; then
  XMP="Xmp.dc.$key"

# Explanation of the new-line (LF) substitution:
#  :a create a label 'a', N append the next line to the pattern space,
#  $! if not the last line, ba branch (go to) label 'a', s substitute,
#  /\n/ regex for new line, /<br>/ by BR tag, /g global match
# Also remove \r (CR) if any, then substitute:

# Substitute line breaks into <br> tags, remove
# the '60ch-label', and any language marker
exiv2 -px -g$XMP $fil 2>/dev/null \
  | sed -e ':a' -e 'N' -e '$!ba' -e's/\r//g' -e 's/\n/<br>/g' \
  | sed 's/^.\{60\}//' \
  | sed 's/^lang=[^\ ]*\ //'
else
  if [[ $keyname == '' ]]; then key='<Xmp.dc-key>'; fi
  echo
  echo "Usage: "`basename $0`" $key <image file name>"
  echo "  Extracts the utf-8 text in Xmp.dc.$key"
  if [[ $keyname == '' ]]; then
    echo "  The key must be one of these items: description,"
    echo "  creator, subject, title, rights, or source"
    echo "  Needs: sed, exiv2"
  fi
  echo
fi
