#! /bin/bash

# Ember-build-script: ember-b-script

# Production catalog
prodcat="../public/"
messcat="../"
# Produce a build stamp message
mestxt='build '`date +%y%m%d-%H%M`
echo "${mestxt} during work with" > ${prodcat}buildstamp.txt
ember b -prod --output-path=$prodcat --watch true

# NOTE: If --watch true is set, the lines below don't
# process until build watch is broken manually with ^C
echo "Producing build timestamp ..."
mestxt='build '`date +%y%m%d-%H%M`
echo $mestxt
hint=' · Not for MS IE · '
echo $mestxt$hint > ${messcat}buildstamp.txt
echo -n "Done. "
date
